Sprint 07
RolledLeaf/MovieQuiz-iOS pull request #4
Opened 2024-09-17 22:43 UTC by RolledLeaf

Не пойму почему в функции func showAnswerResult
константа guard let currentQuestion помечается как неиспользуемая

2024-09-18 08:03 UTC, Kirchberg commented on MovieQuiz/MovieQuizPresenter.swift
> +        }
Не забывай следить за отступами, общепринятые отступы помогают читать код быстрее. 
В общем случае поможет выделить весь файл `cmd+A` и зажать `control+i`

2024-09-18 08:04 UTC, Kirchberg commented on MovieQuiz/MovieQuizPresenter.swift
> +        }
`currentQuestion` дальше в коде ниже нигде не используется, целесообразно проверку убрать

2024-09-18 08:08 UTC, Kirchberg commented on MovieQuiz/MovieQuizPresenter.swift
> +final class MovieQuizPresenter: QuestionFactoryDelegate {
⚠️ В архитектуре MVP необходим не только сам класс `Presenter`, но и его протокол. В данном случае ожидается, что `MovieQuizPresenter` будет подписан под протокол, например, `MovieQuizPresenterProtocol`, который будет содержать методы, необходимые `View/ViewController`.

Полезные статьи на тему архитектуры MVP с примерами:
– [Discover the MVP Architecture](https://www.swiftwithvincent.com/blog/discover-the-mvp-architecture)
– [Swift MVP: A Step-by-Step Guide for Clean Code](https://medium.com/@gbrigens/swift-mvp-a-step-by-step-guide-for-clean-code-869ec8eb4b22)
– [Архитектурные паттерны в iOS](https://habr.com/ru/companies/badoo/articles/281162/)

2024-09-18 08:08 UTC, Kirchberg commented on MovieQuiz/MovieQuizPresenter.swift
> +    }
Если методы не используются, было бы хорошо их удалить

2024-09-18 08:11 UTC, Kirchberg commented on MovieQuiz/MovieQuizPresenter.swift
> +    var viewController: MovieQuizViewControllerProtocol?
⚠️ В классе `MovieQuizPresenter` сожержится сильная ссылка на `viewController`, сам же `MovieQuizViewController` тоже содержит ссылку на `MovieQuizPresenter`, из-за этого будет retain-cycle и утечка памяти.

2024-09-18 08:17 UTC, Kirchberg commented on MovieQuizTests/MoviesLoaderTests.swift
> +    }
⚠️ Необходимо также написать тест на получение ошибки, не только на получение успешного ответа

2024-09-18 08:17 UTC, Kirchberg commented on MovieQuizTests/StubNetworkClient.swift
Пустой файл было бы хорошо удалить

2024-09-18 08:20 UTC, Kirchberg requested changes
Привет, есть пару критических комментариев без исправления которых я не смогу принять работу, оставил их в общем отзыве

2024-09-18 13:12 UTC, RolledLeaf commented on MovieQuizTests/StubNetworkClient.swift
не вижу в этой папке такого файла

2024-09-19 09:29 UTC, Kirchberg commented on MovieQuiz/Services/QuestionFactoryDelegate.swift
> +    }
Не забывай следить за отступами, общепринятые отступы помогают читать код быстрее. 
В общем случае поможет выделить весь файл `cmd+A` и зажать `control+i`

2024-09-19 09:30 UTC, Kirchberg commented on MovieQuizTests/MoviesLoaderTests.swift
> +
Было бы хорошо убрать пустые лишние отступы :)

2024-09-19 09:34 UTC, Kirchberg approved these changes
Работа принята, успехов в следующем задании!

2024-09-26 15:00 UTC, merged